version: '3'

services:
    client:
        build: ./client
        ports:
            - "8080:3000"
        volumes:
            - ./client/src:/app/src
        depends_on:
            - server
    server:
        build: ./server
        ports:
            - "3000:3000"
        command: npm run dev
        volumes:
        - ./server/src/:/app/src/
    mongodb:
        image: mongo
        volumes:
        - ./data:/data/db
